name: Build and Deploy Release
on:
  push:
    branches:
      - cc/test
jobs:
  staging:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: yarn install
      - name: Build App
        run: npm run app:build
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Write Google Services Json
        run: cd maths-club-app/android && echo $secrets.GOOGLE_SERVICES_JSON && echo $secrets.GOOGLE_SERVICES_JSON > app/google-services.json && cat app/google-services.json
      - name: Generate Android Build
        # write google services to json from env, create release app bundle (aab) and app assemble (apk)
        run: cd maths-club-app/android && ./gradlew clean :app:bundleRelease :app:assembleRelease
      - name: Sign Android Bundle
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: maths-club-app/android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY_BASE64 }}
          alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
      # - name: Upload Bundle Release Artificat
      #   uses: actions/upload-artifact@v2
      #   with:
      #     # release file env path added in previous step
      #     path: ${{ env.SIGNED_RELEASE_FILE}}
      - name: Upload to Google play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: io.c2dev.samimathsclub
          releaseFile: ${{ env.SIGNED_RELEASE_FILE}}
          track: beta
          #whatsNewDirectory: /distribution/whatsnew
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:production
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: maths-club-app
