# Create production builds for web and deploy to relevant providers
name: Build and Deploy Staging
on:
  push:
    branches:
      - master
jobs:
  staging:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: yarn install
      - name: Populate Config
        run: echo $FIREBASE_CONFIG_JSON > maths-club-app/src/environments/firebaseConfig.json
        env:
          FIREBASE_CONFIG_JSON: ${{secrets.FIREBASE_CONFIG_JSON}}
      - name: Build
        run: cd maths-club-app && npm run build:prod
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only "hosting:staging,functions"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: maths-club-app
