name: Build IOS
on:
  push:
    branches:
      - ios
jobs:
  ios:
    name: Build IOS
    runs-on: macOS-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: yarn install
      - name: Build App
        run: npm run app:build
      - name: Build IOS
        uses: yukiarrr/ios-build-action@v1.1.0
        with:
          project-path: maths-club-app/ios/App/App.xcodeproj
          p12-base64: ${{ secrets.IOS_P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.IOS_PROVISION_BASE64 }}
          code-signing-identity: iOS Distribution
          team-id: RWK54FS6K5
          output-path: ./maths-club-app/ios/App/build.ipa
          workspace-path: ./maths-club-app/ios/App/App.xcworkspace
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./maths-club-app/ios/App/build.ipa
          asset_name: build.ipa
          asset_content_type: application/zip
