name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    env:
      APP_VERSION: "0.0.0"
    steps:
      # Extract current version number from package.json
      - name: checkout
        uses: actions/checkout@master
      - name: get_version
        run: echo ::set-env name=APP_VERSION::$(echo "$(cat package.json | jq -r '.version')")
      - name: check_version
        run: echo "version $env.APP_VERSION"
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RESOLVED_VERSION: ${{env.APP_VERSION}}
